modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="cool_stuff_to_mess_with"
version="1.0.0"
displayName="Cool Stuff To Mess With"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="erikn, MCreator"

[[dependencies.cool_stuff_to_mess_with]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




